name:  Read a yaml file using python script and store values in GITHUB output or GITHUB environment
run-name: Read yaml and store in output or envrionment

on:
  workflow_dispatch:
    inputs:
      envType:
        description: 'Type'
        required: true
        type: string

jobs:
  read-yaml:
    runs-on: ubuntu-latest
    env:
      INPUT_TYPE: ${{ github.event.inputs.envType }}
      FILE_PATH: '.github/evn-realms.yaml'
      NAME: aman
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run python script to read yaml file
        id: get-details-from-yaml
        run: |
          echo "file_path = ${{ env.FILE_PATH }}"
          python .github/scripts/read-values-from-yaml-file.py
      
      - name: Test whether able to read or not
        run: |
          echo "Name : ${{ env.NAME }}"
          echo "Location: ${{ env.LOCATION }}"
          echo "Work : ${{ env.WORK }}"
      
      - name: Create Dynamic API Endpoint
        run: |
          API_ENDPOINT="https://${NAME}/live"
          echo "API_ENDPOINT=${API_ENDPOINT}"
          echo "API_ENDPOINT=${API_ENDPOINT}" >> $GITHUB_ENV
      
      - name: Check Endpoint
        run: |
          echo "The API Endpoint is ${{env.API_ENDPOINT}}."
