name: Dynamic Secret Names

on:
  push:
    branch:
      -master
  workflow_dispatch:
    inputs:
      name:
        description: 'Enter the name (AMAN_KUMAR or AKASH_KUMAR)'
        required: true

jobs:
  create-secrets:
    runs-on: ubuntu-latest
    env:
      SECRET: ${{ secrets.AKASH_KUMAR }}
    steps:
      - name: Set secret name
        id: set-secret-name
        run: |
          echo "::set-output name=secret_name::${{ github.event.inputs.name }}"

      - name: Create secret
        env:
          SECRET_NAME : "${{ secrets[steps.set-secret-name.outputs.secret_name] }}"
        run: |
          echo "Creating secret ${{ steps.set-secret-name.outputs.secret_name }}"
          echo "${{ env.SECRET_NAME }}"
